#+TITLE: Borges: A Mesos framework for distributed Org Babel runs
#+startup: showeverything

# TODO: logo image
# TODO: borges quote

*** TODO Motivation

Org Babel is good for scheduling workloads locally
or remotely via SSH, and the Borges scheduler just takes it 
to the next level by using Mesos to abstract the resources used
for running the workloads as specified in the Org mode document.

*** TODO Usage examples

For example, having a ~org-file.org~ document with the following content:

#+BEGIN_SRC org
,#+TITLE: Code block that should run forever

,#+name: run-forever
,#+BEGIN_SRC sh 
echo "Started running"
while true; do
  echo "Still running..."
  sleep 1
done
,#+END_SRC
#+END_SRC

We can submit it to the scheduler for execution:

#+BEGIN_SRC sh 
curl -X POST -d@org-file.org 127.0.0.1:8888/org/
#+END_SRC

# Then check its progress on Mesos:
# 
# TODO: Add image
# 

**** COMMENT Using ~borges.el~

- Open an Org mode document
- Set the =#+borgesaddress:= in buffer setting in your document.
- Call ~org-borges-exec~
- Visit the address with the resulting Org mode document.

*** COMMENT Installation

Just get the binary for your platform.

*** COMMENT Hacking

# Etc...
